[project]
name = "image-watermarker"
version = "0.1.0"
description = "Image Watermark Creation Tool"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "flet>=0.28.3",
    "pillow==11.2.1",
]
